version: '3.3'

services:
  sig-provider:
    image: ghcr.io/blockscout/sig-provider:${SIG_PROVIDER_DOCKER_TAG:-main}
    restart: always
    container_name: 'sig-provider'
    ports:
      - 8151:8050
