version: '3.3'

services:
  frontend:
    image: ghcr.io/blockscout/frontend:${FRONTEND_DOCKER_TAG:-main}
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
    ports:
      - 3000:3000
