version: '3.3'

services:
  visualizer:
    image: ghcr.io/blockscout/visualizer:${VISUALIZER_DOCKER_TAG:-latest}
    restart: always
    container_name: 'visualizer'
    env_file:
      -  ../envs/common-visualizer.env
    ports:
      - 8152:8050
